# Generated by Django 4.1.1 on 2022-09-17 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_user_company_user_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='brand',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='price',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='year',
            field=models.TextField(max_length=4, null=True),
        ),
    ]
