# Generated by Django 4.1.1 on 2022-09-17 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_room_brand_room_price_room_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='price',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='year',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
