# Generated by Django 4.1.1 on 2022-09-17 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_room_price_alter_room_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='brand',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
