# Generated by Django 4.1.1 on 2022-09-17 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_room_brand_alter_room_price_alter_room_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='brand',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='room',
            name='price',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='room',
            name='year',
            field=models.CharField(max_length=4),
        ),
    ]
