# Generated by Django 4.1.1 on 2022-09-17 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_room_brand_alter_room_price_alter_room_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='brand',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='price',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='year',
            field=models.TextField(blank=True, null=True),
        ),
    ]
